'use strict';

/*
 * Google Calendar sync. Each doctor pushes THEIR OWN assigned nights to THEIR
 * OWN calendar using the OAuth access token captured at Google sign-in
 * (scope: calendar.events). No server / domain-wide delegation needed.
 *
 * On re-sync we delete previously-created events (tracked by id in the doctor's
 * claim doc) and recreate them, so admin edits / verbal swaps stay in sync
 * without duplicating.
 */
(function (global) {

  const API = 'https://www.googleapis.com/calendar/v3/calendars/primary/events';
  const TZ = 'Asia/Bangkok';
  const SHIFT_START = '16:00:00';
  const SHIFT_END = '08:00:00'; // next morning

  function nextDayKey(dateKey) {
    const [y, m, d] = dateKey.split('-').map(Number);
    const dt = new Date(y, m - 1, d + 1);
    const pad = n => String(n).padStart(2, '0');
    return dt.getFullYear() + '-' + pad(dt.getMonth() + 1) + '-' + pad(dt.getDate());
  }

  function eventBody(dateKey) {
    return {
      summary: 'On-call (Ortho)',
      description: 'Night on-call duty 16:00–08:00. Generated by the ortho call-schedule app.',
      start: { dateTime: dateKey + 'T' + SHIFT_START, timeZone: TZ },
      end: { dateTime: nextDayKey(dateKey) + 'T' + SHIFT_END, timeZone: TZ },
      reminders: { useDefault: false, overrides: [{ method: 'popup', minutes: 120 }] },
    };
  }

  async function call(token, method, path, body) {
    const res = await fetch(API + (path || ''), {
      method,
      headers: { Authorization: 'Bearer ' + token, 'Content-Type': 'application/json' },
      body: body ? JSON.stringify(body) : undefined,
    });
    if (!res.ok && res.status !== 410 && res.status !== 404) {
      throw new Error('Calendar API ' + res.status + ': ' + (await res.text()));
    }
    return res.status === 204 ? null : res.json().catch(() => null);
  }

  /*
   * sync(token, dateKeys, prevEventIds) → { dateKey: eventId }
   *   token        : OAuth access token (from Store.currentUser.accessToken)
   *   dateKeys     : ["YYYY-MM-DD", ...] this doctor's assigned nights
   *   prevEventIds : { dateKey: eventId } from a previous sync (to clean up)
   */
  async function sync(token, dateKeys, prevEventIds) {
    if (!token) throw new Error('No Google access token — sign in with Google to enable calendar sync.');
    prevEventIds = prevEventIds || {};

    // 1) remove stale events from the previous sync
    for (const k of Object.keys(prevEventIds)) {
      try { await call(token, 'DELETE', '/' + prevEventIds[k]); } catch (e) { /* tolerate */ }
    }

    // 2) create fresh events
    const out = {};
    for (const k of dateKeys) {
      const created = await call(token, 'POST', '', eventBody(k));
      if (created && created.id) out[k] = created.id;
    }
    return out;
  }

  global.CalendarSync = { sync };

})(window);
